name: flutter_case
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  
 
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #Route
  auto_route: ^4.2.1
  #Network
  dio: ^4.0.6
  #State Managment  
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  #DI
  get_it: ^7.2.0
  #json parse
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  #.env
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  #Generator
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0

  #Testing
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  http_mock_adapter: ^0.3.3


flutter:

  uses-material-design: true

  assets:
   - .env
